# Generated by Django 5.2.6 on 2025-11-24 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeslot',
            name='meeting_link',
            field=models.URLField(blank=True),
        ),
    ]
